In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("weather_data.csv")
df.head()

          day  temperature  windspeed  event  duration
0  01-01-2017         32.0        6.0   Rain         2
1  01-04-2017          NaN        9.0  Sunny         3
2  01-05-2017         28.0        NaN   Snow         4
3  01-06-2017          NaN        7.0    NaN         5
4  01-07-2017         32.0        NaN   Rain         7

In [2]:
df.tail()

          day  temperature  windspeed   event  duration
4  01-07-2017         32.0        NaN    Rain         7
5  01-08-2017          NaN        NaN   Sunny         5
6  01-09-2017          NaN        NaN     NaN         6
7  01-10-2017         34.0        8.0  Cloudy         4
8  01-11-2017         40.0       12.0   Sunny         2

In [3]:
df.describe()

       temperature  windspeed  duration
count      5.00000   5.000000  9.000000
mean      33.20000   8.400000  4.222222
std        4.38178   2.302173  1.715938
min       28.00000   6.000000  2.000000
25%       32.00000   7.000000  3.000000
50%       32.00000   8.000000  4.000000
75%       34.00000   9.000000  5.000000
max       40.00000  12.000000  7.000000

In [4]:
df.replace(" ",np.nan, inplace = True)

In [6]:
df.head(9)

          day  temperature  windspeed   event  duration
0  01-01-2017         32.0        6.0    Rain         2
1  01-04-2017          NaN        9.0   Sunny         3
2  01-05-2017         28.0        NaN    Snow         4
3  01-06-2017          NaN        7.0     NaN         5
4  01-07-2017         32.0        NaN    Rain         7
5  01-08-2017          NaN        NaN   Sunny         5
6  01-09-2017          NaN        NaN     NaN         6
7  01-10-2017         34.0        8.0  Cloudy         4
8  01-11-2017         40.0       12.0   Sunny         2

In [7]:
df.isnull().sum()

day            0
temperature    4
windspeed      4
event          2
duration       0
dtype: int64

In [8]:
df.dropna()

          day  temperature  windspeed   event  duration
0  01-01-2017         32.0        6.0    Rain         2
7  01-10-2017         34.0        8.0  Cloudy         4
8  01-11-2017         40.0       12.0   Sunny         2

In [9]:
mean_value=df['temperature'].mean()
df['temperature'] = df['temperature'].fillna(mean_value)

In [15]:
mean_v=df['windspeed'].mean() 
new_df = df.fillna({'temperature':0, 
'windspeed':0, 
'event':'no_event'})
new_df

          day  temperature  windspeed     event  duration
0  01-01-2017         32.0        6.0      Rain         2
1  01-04-2017         33.2        9.0     Sunny         3
2  01-05-2017         28.0        0.0      Snow         4
3  01-06-2017         33.2        7.0  no_event         5
4  01-07-2017         32.0        0.0      Rain         7
5  01-08-2017         33.2        0.0     Sunny         5
6  01-09-2017         33.2        0.0  no_event         6
7  01-10-2017         34.0        8.0    Cloudy         4
8  01-11-2017         40.0       12.0     Sunny         2

In [16]:
df.dtypes 
df[["duration"]]=df[["duration"]].astype("float") 
df.head()

          day  temperature  windspeed  event  duration
0  01-01-2017         32.0        6.0   Rain       2.0
1  01-04-2017         33.2        9.0  Sunny       3.0
2  01-05-2017         28.0        NaN   Snow       4.0
3  01-06-2017         33.2        7.0    NaN       5.0
4  01-07-2017         32.0        NaN   Rain       7.0

In [18]:
df3 = df.copy() 
df3 = pd.get_dummies(df3, columns = ['event']) 
display(df3)

,day,temperature,windspeed,duration,event_Cloudy,event_Rain,event_Snow,event_Sunny
0,01-01-2017,32.0,6.0,2.0,False,True,False,False
1,01-04-2017,33.2,9.0,3.0,False,False,False,True
2,01-05-2017,28.0,NaN,4.0,False,False,True,False
3,01-06-2017,33.2,7.0,5.0,False,False,False,False
4,01-07-2017,32.0,NaN,7.0,False,True,False,False
5,01-08-2017,33.2,NaN,5.0,False,False,False,True
6,01-09-2017,33.2,NaN,6.0,False,False,False,False
7,01-10-2017,34.0,8.0,4.0,True,False,False,False
8,01-11-2017,40.0,12.0,2.0,False,False,False,True